"""create Ingredient and Nutrient related tables

Revision ID: 0685c327c50e
Revises: d5b1fbc4c5e2
Create Date: 2025-10-17 14:35:51.434016

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0685c327c50e'
down_revision: Union[str, Sequence[str], None] = 'd5b1fbc4c5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micronutrient',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_micronutrient_name'), 'micronutrient', ['name'], unique=True)
    op.create_table('ingredient',
    sa.Column('ingredient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calories', sa.Numeric(precision=4), nullable=False),
    sa.Column('protein', sa.Numeric(precision=3), nullable=False),
    sa.Column('fat', sa.Numeric(precision=3), nullable=False),
    sa.Column('carbohydrates', sa.Numeric(precision=3), nullable=False),
    sa.Column('glycemic_index', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_index(op.f('ix_ingredient_ingredient_id'), 'ingredient', ['ingredient_id'], unique=True)
    op.create_table('ingredient_micronutrient',
    sa.Column('ingredient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nutrient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ),
    sa.ForeignKeyConstraint(['nutrient_name'], ['micronutrient.name'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'nutrient_name')
    )
    op.add_column('user', sa.Column('password', sa.CHAR(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.drop_table('ingredient_micronutrient')
    op.drop_index(op.f('ix_ingredient_ingredient_id'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_micronutrient_name'), table_name='micronutrient')
    op.drop_table('micronutrient')
    # ### end Alembic commands ###
