"""Add unique constraint between name and created_by in Ingredient table

Revision ID: 235098a0f3c4
Revises: fd63208592ce
Create Date: 2025-10-19 01:10:35.219129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235098a0f3c4'
down_revision: Union[str, Sequence[str], None] = 'fd63208592ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UNIQUE_NAME_CREATEDBY', 'ingredient', ['name', 'created_by'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UNIQUE_NAME_CREATEDBY', 'ingredient', type_='unique')
    # ### end Alembic commands ###
