"""create role table

Revision ID: 3351759245e8
Revises: 3b50e7511c53
Create Date: 2025-09-30 20:05:32.281088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3351759245e8'
down_revision: Union[str, Sequence[str], None] = '3b50e7511c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_index(op.f('ix_role_role'), 'role', ['role'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_role'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
