"""local USDA sync strategy updates

Revision ID: 55e3acc5f184
Revises: 6006f9d93a11
Create Date: 2026-02-12 14:44:29.032055

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e3acc5f184'
down_revision: Union[str, Sequence[str], None] = '6006f9d93a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('usda_id', sa.Integer(), nullable=True))
    op.add_column('ingredient', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('ingredient', 'calories',
               existing_type=sa.NUMERIC(precision=4, scale=0),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=True)
    op.alter_column('ingredient', 'protein',
               existing_type=sa.NUMERIC(precision=3, scale=0),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=True)
    op.alter_column('ingredient', 'fat',
               existing_type=sa.NUMERIC(precision=3, scale=0),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=True)
    op.alter_column('ingredient', 'carbohydrates',
               existing_type=sa.NUMERIC(precision=3, scale=0),
               type_=sa.Numeric(precision=6, scale=2),
               nullable=True)
    op.alter_column('ingredient', 'water',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_ingredient_usda_id'), 'ingredient', ['usda_id'], unique=True)
    op.alter_column('micronutrient', 'usda_id',
               existing_type=sa.NUMERIC(precision=4, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'micronutrient', ['usda_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micronutrient', type_='unique')
    op.alter_column('micronutrient', 'usda_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=0),
               existing_nullable=False)
    op.drop_index(op.f('ix_ingredient_usda_id'), table_name='ingredient')
    op.alter_column('ingredient', 'water',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=1),
               existing_nullable=True)
    op.alter_column('ingredient', 'carbohydrates',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=3, scale=0),
               nullable=False)
    op.alter_column('ingredient', 'fat',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=3, scale=0),
               nullable=False)
    op.alter_column('ingredient', 'protein',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=3, scale=0),
               nullable=False)
    op.alter_column('ingredient', 'calories',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=0),
               nullable=False)
    op.drop_column('ingredient', 'brand')
    op.drop_column('ingredient', 'usda_id')
    # ### end Alembic commands ###
