"""Add USDA Id field to MicroNutrient table to map USDA nutrients with Ingredients from API

Revision ID: 6006f9d93a11
Revises: 6d26c7795c96
Create Date: 2026-02-10 13:13:47.139954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6006f9d93a11'
down_revision: Union[str, Sequence[str], None] = '6d26c7795c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('micronutrient', sa.Column('usda_id', sa.Numeric(precision=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('micronutrient', 'usda_id')
    # ### end Alembic commands ###
