"""Added water as optional field in Ingredient table

Revision ID: 8cb3d9657439
Revises: ba45af73227b
Create Date: 2025-11-27 12:28:01.739170

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb3d9657439'
down_revision: Union[str, Sequence[str], None] = 'ba45af73227b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('water', sa.Numeric(precision=4, scale=1), nullable=True))
    op.alter_column('micronutrient', 'category',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('micronutrient', 'category',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('ingredient', 'water')
    # ### end Alembic commands ###
