"""idek anymore

Revision ID: 9faa8c658fb6
Revises: ecf239a5427e
Create Date: 2026-02-15 04:00:43.570531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9faa8c658fb6'
down_revision: Union[str, Sequence[str], None] = 'ecf239a5427e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption', sa.Column('calories', sa.Float(), nullable=False))
    op.add_column('consumption', sa.Column('protein', sa.Float(), nullable=False))
    op.add_column('consumption', sa.Column('fat', sa.Float(), nullable=False))
    op.add_column('consumption', sa.Column('carbohydrates', sa.Float(), nullable=False))
    op.add_column('consumption', sa.Column('micronutrients', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumption', 'micronutrients')
    op.drop_column('consumption', 'carbohydrates')
    op.drop_column('consumption', 'fat')
    op.drop_column('consumption', 'protein')
    op.drop_column('consumption', 'calories')
    # ### end Alembic commands ###
