"""Removed Not Null constraint from glycemic_index in Ingredient table

Revision ID: cbcf210b3423
Revises: 2d39f67569c1
Create Date: 2026-02-10 10:17:48.576714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcf210b3423'
down_revision: Union[str, Sequence[str], None] = '2d39f67569c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingredient', 'glycemic_index',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'glycemic_index',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               nullable=False)
    op.alter_column('dish', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
