"""Add consumption table and relationships

Revision ID: ecf239a5427e
Revises: 55e3acc5f184
Create Date: 2026-02-13 17:55:04.024936

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf239a5427e'
down_revision: Union[str, Sequence[str], None] = '55e3acc5f184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption',
    sa.Column('consumption_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=True),
    sa.Column('dish_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(ingredient_id IS NOT NULL AND dish_id IS NULL) OR (ingredient_id IS NULL AND dish_id IS NOT NULL)', name='check_ingredient_xor_dish'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.dish_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consumption_id')
    )
    op.create_index(op.f('ix_consumption_consumption_id'), 'consumption', ['consumption_id'], unique=True)
    op.create_index(op.f('ix_consumption_user_id'), 'consumption', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumption_user_id'), table_name='consumption')
    op.drop_index(op.f('ix_consumption_consumption_id'), table_name='consumption')
    op.drop_table('consumption')
    # ### end Alembic commands ###
