"""Fix relationships with Ingredient and MicroNutrient tables and aswell as relation table. Added quantity to Ingredient_MicroNutrient table

Revision ID: fd63208592ce
Revises: 0685c327c50e
Create Date: 2025-10-19 01:02:23.092415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd63208592ce'
down_revision: Union[str, Sequence[str], None] = '0685c327c50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_micronutrient', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_micronutrient', 'quantity')
    # ### end Alembic commands ###
