"""Created Dish and Ingredient_Dish tables

Revision ID: ff15b2b32f82
Revises: 5e311bc00be2
Create Date: 2025-11-29 16:28:00.459166

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff15b2b32f82'
down_revision: Union[str, Sequence[str], None] = '5e311bc00be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('dish_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('servings', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('dish_id'),
    sa.UniqueConstraint('name', 'created_by', name='UNIQUE_DISH_NAME_CREATEDBY')
    )
    op.create_index(op.f('ix_dish_dish_id'), 'dish', ['dish_id'], unique=True)
    op.create_table('ingredient_dish',
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.dish_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_dish')
    op.drop_index(op.f('ix_dish_dish_id'), table_name='dish')
    op.drop_table('dish')
    # ### end Alembic commands ###
